spring:
  application:
    name: notification-service
  #  Database configuration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:35432/notification_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #    RabbitMQ configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  #    Email configuration for sending notifications
  mail:
    host: ${MAIL_HOST:127.0.0.1}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:PLACEHOLDER}
    password: ${MAIL_PASSWORD:PLACEHOLDER}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#    Notification Events configuration for RabbitMQ
notifications:
  order-events-exchange: orders-exchange
  new-orders-queue: new-orders
  delivered-orders-queue: delivered-orders
  cancelled-orders-queue: cancelled-orders
  error-orders-queue: error-orders
  support-email: support@bookstore.com

server:
  port: 8083
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full