spring:
  application:
    name: order-service
  #  Database configuration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:25432/order_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    open-in-view: false
  #    RabbitMQ configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

#    Order Events configuration for RabbitMQ
orders:
  order-events-exchange: orders-exchange
  new-orders-queue: new-orders
  delivered-orders-queue: delivered-orders
  cancelled-orders-queue: cancelled-orders
  error-orders-queue: error-orders

server:
  port: 8082
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full